### ISSUE TITLE
Couldn't find preset "stage-0"

### ISSUE THREAD

**Issue by justincatalana** [gauravtiwari/browserify_on_rails#1]
Got here from react-rails.
I'm getting this error, with a fresh build of your application and trying to visit the root.

Error: Couldn't find preset "stage-0"

**Comment by justincatalana** [comment]
Just removed stage-0 from .babelrc and it's working

**Comment by gauravtiwari** [comment]
Great! You could install it though using `npm install babel-preset-stage-0 --save-dev`
