### ISSUE TITLE
If using vue

### ISSUE THREAD

**Issue by zhiephie** [gauravtiwari/browserify_on_rails#2]
I want to ask, if using vuejs what should I change

Thanks

**Comment by gauravtiwari** [comment]
@zhiephie You have to remove react related code and switch it with vue code (https://vuejs.org/v2/guide/). Please take a look at this repo, https://github.com/gauravtiwari/rails-webpacker (Webpack is coming to Rails).

**Comment by zhiephie** [comment]
Thanks @gauravtiwari
